server:
  port: 4000
  shutdown: graceful
spring:
  datasource:
    url: jdbc:postgresql://localhost:5542/hortdb
    username: hort
    password: hort

  lifecycle:
    timeout-per-shutdown-phase: 30s  # espera total del apagado

  task:
    execution:
      shutdown:
        await-termination: true
        await-termination-period: 30s
    scheduling:
      shutdown:
        await-termination: true

  flyway:
    enabled: true
    # usa y crea el schema 'hort' (¡primera vez listo!)
    create-schemas: true
    schemas: hort
    default-schema: hort

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: hort
        jdbc.time_zone: UTC

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/Hort
          jwk-set-uri: http://localhost:8180/realms/Hort/protocol/openid-connect/certs
